const os = require('node:os')

console.log('informacion del sistema operativo')
console.log('---------------')
console.log('nombre del sistema operativo', os.platform())
console.log('version del sistema operativo', os.release())
console.log('arquitectura', os.arch())
console.log('cpu', os.cpus())
console.log('memoria libre',os.freemem())
console.log('memoria total', os.totalmem())
console.log('uptime', os.uptime()/60)